import type { ArchetypeDef, ArchetypeId } from "./types";

// Tính cách khách là xu hướng, không phải định kiến: cùng một cách phục vụ, mỗi nhóm khách cảm nhận khác nhau.
export const ARCHETYPES: Record<ArchetypeId, ArchetypeDef> = {
  hurried: {
    id: "hurried",
    name: "Khách vội",
    description: "Biết mình cần gì, muốn mua nhanh rồi đi.",
    spawnWeight: 3,
    patienceMs: [18000, 26000],
    reviewProbability: 0.25,
    priceSensitivity: 0.3,
    strictness: 0.05,
    waitWeight: 1.5,
    likesDetail: false,
    backorderChance: 0.25,
    requestWeights: {
      "named-mask": 3,
      "named-bandage": 3,
      "named-sunscreen": 2,
      "named-sanitizer": 3,
      "named-lipbalm": 2,
      "named-soap": 2,
      "named-tissues": 3,
      "named-wipes": 2,
      "named-toothbrush": 1,
      "named-toothpaste": 1,
      "named-comb": 1,
      "named-gauze": 1,
      "need-dust": 1,
      "need-picnic": 1,
      "refer-fever": 0.6,
    },
  },
  curious: {
    id: "curious",
    name: "Khách hay hỏi",
    description: "Kể nhu cầu và muốn được gợi ý, kiên nhẫn hơn.",
    spawnWeight: 2,
    patienceMs: [34000, 48000],
    reviewProbability: 0.35,
    priceSensitivity: 0.5,
    strictness: 0,
    waitWeight: 0.8,
    likesDetail: true,
    backorderChance: 0.7,
    requestWeights: {
      "named-sunscreen": 1,
      "named-lipbalm": 1,
      "need-beach": 3,
      "need-dust": 2,
      "need-scrape": 3,
      "need-picnic": 2,
      "need-dry-lips": 3,
      "need-handwash": 2,
      "need-quick-clean": 2,
      "need-makeup": 2,
      "need-between-teeth": 2,
      "need-moisture": 2,
      "need-facewash": 2,
      "need-hands": 2,
      "refer-dizzy": 0.8,
      "refer-fever": 0.4,
    },
  },
  demanding: {
    id: "demanding",
    name: "Khách khó tính",
    description:
      "Kỳ vọng cao, để ý giá và hay viết đánh giá — kể cả khi được phục vụ đúng.",
    spawnWeight: 1.2,
    patienceMs: [24000, 34000],
    reviewProbability: 0.6,
    priceSensitivity: 0.9,
    strictness: 0.3,
    waitWeight: 1.2,
    likesDetail: false,
    backorderChance: 0.35,
    requestWeights: {
      "named-sunscreen": 3,
      "named-sanitizer": 2,
      "named-mask": 1,
      "named-lipbalm": 1,
      "named-cottonpads": 2,
      "named-floss": 1,
      "named-moisturizer": 2,
      "named-cleanser": 2,
      "named-handcream": 2,
      "need-beach": 2,
      "need-picnic": 1,
      "refer-fever": 0.5,
    },
  },
  careful: {
    id: "careful",
    name: "Khách chuẩn bị kỹ",
    description:
      "Hay mua đồ dùng cho gia đình và túi sơ cứu, thích nghe giải thích rõ ràng.",
    spawnWeight: 1.7,
    patienceMs: [30000, 42000],
    reviewProbability: 0.32,
    priceSensitivity: 0.45,
    strictness: 0.08,
    waitWeight: 0.9,
    likesDetail: true,
    backorderChance: 0.6,
    requestWeights: {
      "named-gauze": 2,
      "named-tape": 2,
      "named-elasticbandage": 2,
      "named-cottonswab": 2,
      "named-soap": 1,
      "named-wipes": 1,
      "need-gauze": 3,
      "need-tape": 3,
      "need-wrap": 3,
      "need-small-cotton": 2,
      "need-handwash": 1,
      "refer-dizzy": 0.6,
    },
  },
  thrifty: {
    id: "thrifty",
    name: "Khách cân nhắc giá",
    description: "Xem giá kỹ trước khi mua, vui khi giá hợp lý.",
    spawnWeight: 1.6,
    patienceMs: [28000, 39000],
    reviewProbability: 0.38,
    priceSensitivity: 0.85,
    strictness: 0.08,
    waitWeight: 0.9,
    likesDetail: false,
    backorderChance: 0.55,
    requestWeights: {
      "named-tissues": 2,
      "named-cottonpads": 2,
      "named-toothbrush": 2,
      "named-toothpaste": 2,
      "named-floss": 2,
      "named-comb": 2,
      "need-paper": 2,
      "need-brush": 2,
      "need-paste": 2,
      "need-hair": 2,
      "need-moisture": 1,
      "need-dry-lips": 1,
      "refer-fever": 0.5,
    },
  },
};

export const ARCHETYPE_IDS = Object.keys(ARCHETYPES) as ArchetypeId[];
