import type { ProductDef, ProductId } from "./types";

// Danh mục hư cấu, chỉ gồm đồ chăm sóc cá nhân/sơ cứu không kê đơn. Giá là số cân bằng tạm thời.
// Kem chống nắng và nước rửa tay đang bán cao hơn giá tham khảo: khách nhạy giá sẽ phàn nàn về chính sách giá.
export const PRODUCTS: Record<ProductId, ProductDef> = {
  mask: {
    id: "mask",
    name: "Khẩu trang",
    brand: "Mây Nhẹ",
    category: "hygiene",
    price: 12,
    cost: 6,
    referencePrice: 12,
    shelfCapacity: 6,
  },
  bandage: {
    id: "bandage",
    name: "Băng dán cá nhân",
    brand: "Dán Xinh",
    category: "first-aid",
    price: 10,
    cost: 4,
    referencePrice: 10,
    shelfCapacity: 6,
  },
  sunscreen: {
    id: "sunscreen",
    name: "Kem chống nắng",
    brand: "Nắng Dịu",
    category: "skin-care",
    price: 30,
    cost: 15,
    referencePrice: 25,
    shelfCapacity: 4,
  },
  sanitizer: {
    id: "sanitizer",
    name: "Nước rửa tay khô",
    brand: "Tay Sạch",
    category: "hygiene",
    price: 18,
    cost: 8,
    referencePrice: 16,
    shelfCapacity: 5,
  },
  lipbalm: {
    id: "lipbalm",
    name: "Son dưỡng môi",
    brand: "Môi Mềm",
    category: "skin-care",
    price: 15,
    cost: 6,
    referencePrice: 15,
    shelfCapacity: 6,
  },
  soap: {
    id: "soap",
    name: "Xà phòng rửa tay",
    brand: "Bọt Mây",
    category: "hygiene",
    price: 12,
    cost: 5,
    referencePrice: 12,
    shelfCapacity: 6,
  },
  tissues: {
    id: "tissues",
    name: "Khăn giấy",
    brand: "Giấy Êm",
    category: "hygiene",
    price: 11,
    cost: 5,
    referencePrice: 11,
    shelfCapacity: 6,
  },
  wipes: {
    id: "wipes",
    name: "Khăn ướt",
    brand: "Mát Tay",
    category: "hygiene",
    price: 14,
    cost: 6,
    referencePrice: 14,
    shelfCapacity: 5,
  },
  cottonpads: {
    id: "cottonpads",
    name: "Bông tẩy trang",
    brand: "Bông Dịu",
    category: "hygiene",
    price: 17,
    cost: 8,
    referencePrice: 17,
    shelfCapacity: 5,
  },
  toothbrush: {
    id: "toothbrush",
    name: "Bàn chải đánh răng",
    brand: "Nụ Cười",
    category: "hygiene",
    price: 16,
    cost: 7,
    referencePrice: 16,
    shelfCapacity: 5,
  },
  toothpaste: {
    id: "toothpaste",
    name: "Kem đánh răng",
    brand: "Nụ Cười",
    category: "hygiene",
    price: 19,
    cost: 9,
    referencePrice: 19,
    shelfCapacity: 5,
  },
  floss: {
    id: "floss",
    name: "Chỉ nha khoa",
    brand: "Sợi Mềm",
    category: "hygiene",
    price: 14,
    cost: 6,
    referencePrice: 14,
    shelfCapacity: 5,
  },
  cottonswab: {
    id: "cottonswab",
    name: "Tăm bông",
    brand: "Bông Dịu",
    category: "hygiene",
    price: 10,
    cost: 4,
    referencePrice: 10,
    shelfCapacity: 6,
  },
  comb: {
    id: "comb",
    name: "Lược bỏ túi",
    brand: "Tóc Gọn",
    category: "hygiene",
    price: 13,
    cost: 6,
    referencePrice: 13,
    shelfCapacity: 5,
  },
  gauze: {
    id: "gauze",
    name: "Gạc sạch",
    brand: "Vải Mềm",
    category: "first-aid",
    price: 13,
    cost: 6,
    referencePrice: 13,
    shelfCapacity: 6,
  },
  tape: {
    id: "tape",
    name: "Băng dính y tế",
    brand: "Dán Xinh",
    category: "first-aid",
    price: 12,
    cost: 5,
    referencePrice: 12,
    shelfCapacity: 6,
  },
  elasticbandage: {
    id: "elasticbandage",
    name: "Băng thun",
    brand: "Vải Mềm",
    category: "first-aid",
    price: 20,
    cost: 10,
    referencePrice: 20,
    shelfCapacity: 4,
  },
  moisturizer: {
    id: "moisturizer",
    name: "Sữa dưỡng ẩm",
    brand: "Mây Dịu",
    category: "skin-care",
    price: 24,
    cost: 12,
    referencePrice: 24,
    shelfCapacity: 5,
  },
  cleanser: {
    id: "cleanser",
    name: "Sữa rửa mặt",
    brand: "Mây Dịu",
    category: "skin-care",
    price: 22,
    cost: 11,
    referencePrice: 22,
    shelfCapacity: 5,
  },
  handcream: {
    id: "handcream",
    name: "Kem dưỡng tay",
    brand: "Mây Dịu",
    category: "skin-care",
    price: 18,
    cost: 8,
    referencePrice: 18,
    shelfCapacity: 5,
  },
};

export const PRODUCT_IDS = Object.keys(PRODUCTS) as ProductId[];
