import type { RejectReason } from "@pharmacy/simulation";

export const REJECT_TEXT: Record<RejectReason, string> = {
  "operations-already-chosen": "Hôm nay đã chốt cách xử lý sự cố.",
  "operations-no-case": "Hôm nay không có sự cố này.",
  "transfer-not-pending": "Chưa có quyết định điều chuyển.",
  "transfer-pending": "Hãy nhận quyết định điều chuyển trước.",
  "unknown-worker": "Không tìm thấy nhân viên.",
  "worker-busy": "Dược sĩ đang bận, đợi xong việc hiện tại nhé.",
  "unknown-customer": "Khách đã rời đi.",
  "customer-not-at-counter": "Khách chưa tới quầy.",
  "customer-already-served": "Khách này đang được phục vụ.",
  "unknown-order": "Lượt phục vụ không còn nữa.",
  "invalid-order-state": "Đợi dược sĩ làm xong bước hiện tại.",
  "unknown-product": "Không có sản phẩm này.",
  "out-of-stock": "Kệ đã hết món này — chạm vào ô hết hàng để nhập thêm.",
  "safety-referral-required":
    "Khách đang mô tả triệu chứng. Hãy khuyên khách đi khám.",
  "insufficient-funds": "Không đủ xu.",
  "shelf-full": "Kệ đã đầy.",
  "invalid-quantity":
    "Số lượng nhập phải là số nguyên và không vượt chỗ trống trên kệ.",
  "counter-assigned-elsewhere":
    "Quầy đang giao cho nhân viên khác — chạm “Tự phục vụ” để nhận lại.",
  "not-your-order": "Khách này đang do nhân viên khác phục vụ.",
  "unknown-candidate": "Không tìm thấy ứng viên.",
  "already-hired": "Người này đã làm ở tiệm rồi.",
  "staff-full":
    "Đội đã đủ chỗ. Nâng Cửa hàng hoặc mua Quầy 2 ở tab Mở rộng để tuyển thêm.",
  "unknown-counter": "Không tìm thấy quầy.",
  "unknown-upgrade": "Không có nâng cấp này.",
  "already-owned": "Đã có nâng cấp này.",
  "level-locked": "Chưa đạt cấp tiệm cần thiết.",
  "product-locked": "Món này chưa được mở trong kho và cửa hàng.",
  "previous-level-required": "Cần mua cấp trước của vật dụng này.",
  "unknown-complaint": "Không tìm thấy khiếu nại.",
  "complaint-closed": "Khiếu nại này đã được phản hồi.",
  "price-out-of-range":
    "Giá phải cao hơn giá vốn và không vượt quá 1,5 lần giá tham khảo.",
  "cannot-dismiss-player": "Bạn là chủ tiệm, không thể tự cho mình nghỉ.",
  "worker-off-duty": "Người này đang ngoài ca làm — xếp thêm ca ở tab Nhân sự.",
  "store-already-open": "Tiệm đã mở cửa rồi.",
  "unknown-prep-task": "Không có việc chuẩn bị này.",
  "prep-already-done": "Việc này đã làm xong.",
  "invalid-shifts": "Mỗi nhân viên cần ít nhất một ca.",
  "cannot-schedule-player": "Bạn là quản lý, luôn có mặt ở tiệm.",
  "shift-full":
    "Ca này đã đủ người. Nâng Cửa hàng hoặc mua Quầy 2 để thêm chỗ mỗi ca.",
  "worker-not-arrived": "Nhân viên chưa tới ca, đợi thêm chút.",
  "unknown-recruit": "Ứng viên này không còn trong danh sách.",
  "reroll-used": "Hôm nay đã làm mới danh sách rồi, mai quay lại nhé.",
  "not-resigning": "Người này không xin nghỉ.",
  "nothing-hidden": "Ứng viên này không có gì cần tìm hiểu thêm.",
  "unknown-station": "Không có vị trí này.",
  "station-full": "Vị trí này đã đủ người.",
  "unknown-delivery": "Đơn ship này không còn nữa.",
  "delivery-not-packing": "Đơn này đã gói xong.",
  "delivery-not-packed": "Gói đủ món vào đơn trước khi gửi.",
  "delivery-already-sent": "Đơn đã giao cho shipper, không đổi được nữa.",
};
